name: brazil_senate
version: "1.0.0"
config-version: 2

profile: brazil_senate

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

seeds:
  brazil_senate:
    +schema: seeds
    +quote_columns: false

models:
  brazil_senate:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
      dimensions:
        +tags: ['dimensions']
      facts:
        +tags: ['facts']
      bridges:
        +tags: ['bridges']
      aggregations:
        +tags: ['aggregations']
