version: 2

models:
  - name: dim_senador
    description: "One row per senator currently in office — biographical + mandate data"
    columns:
      - name: senador_id
        description: "Unique senator code from the Senate API"
        data_tests:
          - not_null
          - unique

      - name: nome_parlamentar
        data_tests:
          - not_null

      - name: partido_sigla
        data_tests:
          - not_null

      - name: estado_sigla
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['AC','AL','AP','AM','BA','CE','DF','ES','GO','MA','MT',
                         'MS','MG','PA','PB','PR','PE','PI','RJ','RN','RS','RO',
                         'RR','SC','SP','SE','TO']

      - name: mandato_inicio
        data_tests:
          - not_null

      - name: sexo
        data_tests:
          - accepted_values:
              arguments:
                values: ['Masculino', 'Feminino']

  - name: dim_partido
    description: "One row per political party registered at TSE"
    columns:
      - name: partido_sigla
        data_tests:
          - not_null
          - unique

      - name: partido_nome
        data_tests:
          - not_null
